apiVersion: apps/v1
kind: Deployment
metadata:
  name: network-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: network-test
  template:
    metadata:
      labels:
        app: network-test
    spec:
      containers:
      - name: busybox
        image: busybox
        command:
          - sleep
          - "3600"
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 8.8.8.8
          - 8.8.4.4
